# Generated by Django 2.2.3 on 2019-11-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='content', verbose_name='文章内容'),
        ),
    ]
